### ISSUE TITLE
[DOCS] Document required `permissions` setting

### ISSUE THREAD

**Issue by ringods** [guibranco/github-status-action-v2#138]
### Description

Using the new Github Actions `permissions` block, it is possible to give the generated `GITHUB_TOKEN` elevated permissions.

https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token

When using this option, please document which of the settings from the above page is required to make this Github Action work correctly.

**Comment by guibranco** [comment]
Thanks @ringods, updating the docs to include `permissions` in the example.
