### ISSUE TITLE
Timeout with a proxy ETIMEDOUT

### ISSUE THREAD

**Issue by williamfgc** [guibranco/github-status-action-v2#59]
The action times out when trying using it from a self-hosted node behind a proxy. 
It errors out with a [timeout as in this workflow](https://github.com/JuliaORNL/JACC.jl/actions/runs/7879216951/job/21499082933#step:4:483). 
Any help would be appreciated, and thanks for making this action available.

**Comment by Geekdude** [comment]
I was able to resolve this issue by rebuilding the github-status-action-v2 repo and updating the Octokit API calls to use .rest.

See https://github.com/guibranco/github-status-action-v2/pull/60

**Comment by guibranco** [comment]
@Geekdude, big thanks for your outstanding effort on this pull request! I would greatly appreciate your contributions. 🙌

@williamfgc, could you please test the new version and confirm that is now working?

**Comment by williamfgc** [comment]
Fixed by #60
