### ISSUE TITLE
DOCS in the GH actions market place is outdated

### ISSUE THREAD

**Issue by kasir-barati** [guibranco/github-status-action-v2#75]
### Description

Hey hey

Cheers to this GH action :clinking_glasses:. Could we update the docs in the GitHub actions marketplace too? When I read this https://github.com/marketplace/actions/github-status-action-v2 I was using `guibranco/github-status-action-v2@v1.1.9` and then I got this error: 

```
Error: Unable to resolve action `guibranco/github-status-action-v2@v1.1.9`, unable to find version `v1.1.9`
```

**Yeah, I know we do not have that version but that is what I read in the market place doc :grin:**
![image](https://github.com/guibranco/github-status-action-v2/assets/73785723/0af78734-bfec-4c6d-bafc-3633527d1ce2)

I opened a PR for it. I appreciate it if you could look at it :pray:.

**Comment by kasir-barati** [comment]
GOD, I had opened a PR for Sibz repo :disappointed: :sweat:

**Comment by guibranco** [comment]
No worries, one day, he will be back and review all the outstanding PRs, I hope hahaha
